### ISSUE TITLE
Optional plugins and optional packer

### ISSUE THREAD

**Issue by horseinthesky** [wbthomason/packer.nvim#237] opened 2021-02-27 12:30 UTC
Hello.
I've just started the transition from VIM script to lua and decided to start with plugin manager. The first questions come to mind:
1) As far as I understood there are `optional` plugins and `start` plugins. But I could find the difference between them. Why should I install a plugin as `opt` plugin? Or in general, should I? The same is about start plugins. Wy should `packer` be installed as an `opt` plugin? And if it should?
2) I have some install options in VIm Plug:
```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }
```

It seems to work but I just want to clarify if I did it correctly:
```
  use {
    'junegunn/fzf.vim',
    requires = {
      'junegunn/fzf',
      run = 'cd ~/.fzf && ./install --all',
    },
  }
  use {
    'kkoomen/vim-doge',
    run = ':call doge#install()',
    config = function()
      vim.g.doge_doc_standard_python = 'google'
    end,
  }
``` 

3) While doing the transition I want my lua setup to be loaded only for NVIM 0.5 so I added this to my `init.vim`.
So I added this to load lua configs only for 0.5
```
if has('nvim-0.5')
  :lua require'setup'
endif                
```

and then in my setup.lua I have
```
local fn = vim.fn
local execute = vim.api.nvim_command

-- Sensible defaults
require('settings')

-- Auto install packer.nvim if not exists
local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end
vim.cmd [[packadd packer.nvim]]
vim.cmd 'autocmd BufWritePost plugins.lua PackerCompile' -- Auto compile when there are changes in plugins.lua

-- Install plugins
require('plugins')

-- Setup Lua language server using submodule
require('lsp')
```

But whatever NVIM 0.4.3 or 0.5 I run it always loads lsp_config and packer plugins
```
Invalid Neovim version for packer.nvim!
Error detected while processing /home/horseinthesky/.local/share/nvim/site/pack/packer/start/nvim-lspconfig
/plugin/lspconfig.vim:
line   11:
E5105: Error while calling lua chunk: .../pack/packer/start/nvim-lspconfig/lua/lspconfig/util.lua:11: attem
pt to index local 'lsp' (a nil value)
Error detected while processing /home/horseinthesky/.local/share/nvim/site/pack/packer/start/nvim-treesitte
r/plugin/nvim-treesitter.vim:
line   15:
E5105: Error while calling lua chunk: ...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:2: nvim-t
reesitter requires a more recent Neovim nightly version!
```

Even if I do
```
rm .config/nvim/plugin/packer_compiled.vim
```
it still loads lsp and packer.

I need to remove everything packer related to be able to load NVIM 0.4.3:
```
rm -rf .local/share/nvim/site/pack
```

Is there a way to achieve what I want - packer only for NVIM 0.5?

Thank you.

**Comment by Shougo** [comment] 2021-02-28 01:42
You need to to use Nvim 0.5 to use treesitter.

**Comment by nanotee** [comment] 2021-02-28 14:04
1. `packages` are a (Neo)Vim feature, you can read about them in `:help packages`. The gist of it is, `start` packages are always available and loaded every time you start nvim, while `opt` packages are loaded on-demand with the `:packadd` command. This is what `packer` uses to conditionally load plugins.
    `packer` itself doesn't run any code until you call `require('packer')`, so it should be fine to keep it as a `start` package.
2. The snippet looks fine to me!
3. Ah, the problem here is that by default, `packer` puts `packer_compiled.vim` in a `plugin/` directory. Neovim picks up any file in `plugin/` and runs it. One solution would be to put your `packer_compiled.vim` file in a custom directory (like `packer/` for example):
    ```lua
    local packer = require('packer')
    local util = require('packer.util')

    packer.init {
        compile_path = util.join_paths(vim.fn.stdpath('config'), 'packer', 'packer_compiled.vim')
    }

    packer.startup(function(use)
        -- use 'foo/bar' etc
    end)
    ```

    Then, in your `init.vim`:

    ```vim
    if has('nvim-0.5')
        lua require'setup'
        runtime! packer/packer_compiled.vim
    endif
    ```

    You might also want to make sure `nvim-lspconfig` and `nvim-treesitter` are only loaded for Neovim 0.5:

    ```lua
    use {'neovim/nvim-lspconfig', cond = "vim.fn.has('nvim-0.5') == 1"}
    use {'nvim-treesitter/nvim-treesitter', cond = "vim.fn.has('nvim-0.5') == 1"}
    ```

**Comment by horseinthesky** [comment] 2021-02-28 15:04
@nanotee Thank you for detailed answer.

1) `:h packages` says:
```
When Vim starts up, after processing your .vimrc, it scans all directories in 'packpath' for plugins under the "pack/*/start" directory.
```

So my condition
```
if has('nvim-0.5')
    lua require'setup'
endif
```
doesn't make any sense since every plugin installed in `pack/*/start` is loaded whatever NVIM version is launched.
This is exactly what I'm trying to avoid.

The solution should be to set every plugin as opt?!

3) Adding a `cond` to `packer use` automatically makes the plugin `opt`. Is it expected behavior?
```
ll .local/share/nvim/site/pack/packer/opt
drwxr-xr-x horseinthesky horseinthesky 4 KB Sun Feb 28 17:47:28 2021  completion-nvim
drwxr-xr-x horseinthesky horseinthesky 4 KB Sun Feb 28 17:47:29 2021  nvim-lspconfig
drwxr-xr-x horseinthesky horseinthesky 4 KB Sun Feb 28 17:47:32 2021  nvim-treesitter
drwxr-xr-x horseinthesky horseinthesky 4 KB Sun Feb 28 17:47:22 2021  packer.nvim
```

This is my config
```
...
  use {
    'neovim/nvim-lspconfig',
    cond = function()
      return vim.fn.has('nvim-0.5') == 1
    end,
  }
  use {
    'nvim-lua/completion-nvim',
    cond = function()
      return vim.fn.has('nvim-0.5') == 1
    end,
  }
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    cond = function()
      return vim.fn.has('nvim-0.5') == 1
    end,
    config = function()
      require'nvim-treesitter.configs'.setup {
        ensure_installed = 'maintained',
        highlight = {
          enable = true,
        },
      }
    end,
  }
 ...
 ```

All 'opt` plugins a not loaded by packer. This is what I get when running NVIM 0.5 with this config:
```
E5108: Error executing lua /home/horseinthesky/.config/nvim/lua/lsp.lua:2: module 'lspconfig' not found:
        no field package.preload['lspconfig']
        no file './lspconfig.lua'
        no file '/home/horseinthesky/neovim/.deps/usr/share/luajit-2.1.0-beta3/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig/init.lua'
        no file '/home/horseinthesky/neovim/.deps/usr/share/lua/5.1/lspconfig.lua'
        no file '/home/horseinthesky/neovim/.deps/usr/share/lua/5.1/lspconfig/init.lua'
        no file './lspconfig.so'
        no file '/usr/local/lib/lua/5.1/lspconfig.so'
        no file '/home/horseinthesky/neovim/.deps/usr/lib/lua/5.1/lspconfig.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
 and
 ```
 Error running config for nvim-treesitter
Error in packer_compiled: Vim(lua):E5108: Error executing lua [string ":lua"]:15: Vim:E484: Can't open file
 /home/horseinthesky/.local/share/nvim/site/pack/packer/start/nvim-treesitter/lockfile.json
Please check your config for correctness
```

**Comment by nanotee** [comment] 2021-02-28 17:18
> The solution should be to set every plugin as opt?!

Well, at least the plugins that don't work in Neovim 0.4. `fzf` and the like should work fine with both 0.4 and 0.5

> 1. Adding a `cond` to `packer use` automatically makes the plugin `opt`. Is it expected behavior?

Yes, since `start` packages are always loaded, `packer` makes a plugin `opt` when there's a condition for loading it

> All 'opt` plugins a not loaded by packer. This is what I get when running NVIM 0.5 with this config:

Ah, I'm not sure what your config looks like so I might have messed up the order of the `:runtime!` command. Does it work if you run it before `lua require'setup'`? Alternatively, you could require your `~/.config/nvim/lua/lsp.lua` file with the `config` key:

```lua
use {
  'neovim/nvim-lspconfig',
  cond = function()
    return vim.fn.has('nvim-0.5') == 1
  end,
  config = function()
    require'lsp'
  end,
}
```

Not sure what's causing the `nvim-treesitter` error, there seems to be a problem with `lockfile.json`. I don't know if this is because of `packer`

**Comment by horseinthesky** [comment] 2021-02-28 17:35
@nanotee 

`init.vim` has
```
if has('nvim-0.5')
  runtime! packer/packer_compiled.vim
  lua require 'setup'
endif
```
I tried putting `runtime!` both before and after `require 'setup'`.

`setup.lua` looks like this:
```
local fn = vim.fn
local execute = vim.api.nvim_command

-- Auto install packer.nvim if not exists
local install_path = fn.stdpath('data') .. '/site/pack/packer/opt/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end
vim.cmd [[packadd packer.nvim]]
vim.cmd 'autocmd BufWritePost plugins.lua PackerCompile' -- Auto compile when there are changes in plugins.lua

-- Install plugins
require('plugins')

-- Setup Lua language server using submodule
require('lsp')
```

And finally `plugins.lua`:
```
local packer = require('packer')
local util = require('packer.util')

packer.init {
    compile_path = util.join_paths(vim.fn.stdpath('config'), 'packer', 'packer_compiled.vim')
}

return packer.startup(function()

  -- Packer can manage itself as an optional plugin
  use {
    'wbthomason/packer.nvim',
    cond = function()
      return vim.fn.has('nvim-0.5') == 1
    end,
    config = function()
      require 'lsp'
    end,
  }
  ...
```

This thing is it just doesn't load any opt plugin.
Am I missing something?

And btw it still compiles `packer.nvim` to `~/.config/nvim/plugin/`.

**Comment by horseinthesky** [comment] 2021-02-28 18:36
@nanotee 
I think the key is somewhere around this:
```
-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]
```

It seems like packer doesn't load any `opt` plugin. I need explicitly put:
```
vim.cmd [[packadd p<plugin_name>]
```
for every opt plugin. (I've checked. It works.)

Is there a way to make packer load opt plugins?

**Comment by nanotee** [comment] 2021-02-28 19:18
I'm not sure what's happening, it should load them automatically

I've been trying to reproduce this without success, everything works correctly on my end.

Just to make sure: are you re-sourcing `plugins.lua` with `:luafile` before compiling the config? It's possible `packer` isn't reloading your config file before the compilation, and is thus working with an old version of your config

**Comment by horseinthesky** [comment] 2021-02-28 20:06
> Just to make sure: are you re-sourcing `plugins.lua` with `:luafile` before compiling the config? It's possible `packer` isn't reloading your config file before the compilation, and is thus working with an old version of your config
I don't do `:luafile` anywhere.

To make sure it is working with the latest files I close NVIM then do
```
rm -rf .config/nvim/packer
rm -rf .local/share/nvim/site/pack
```

Then I open NVIM, it installs packer due to:
```
if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end
```
in my `setup.lua`

Then I do
```
:PackerInstall
:PackerCompile
```
from NVIM.

Restart NVIM and get error messages. Am I missing something?

**Comment by nanotee** [comment] 2021-02-28 22:09
I'm really not sure what's going on... I tried these exact steps and I still can't reproduce the issue. Here's the config I used if you want to try it yourself:

<details>
<summary>init.vim</summary>

```vim
if has('nvim-0.5')
  runtime! packer/packer_compiled.vim
  lua require 'setup'
endif
```
</details>

<details>
<summary>lua/setup.lua</summary>

```lua
local fn = vim.fn
local execute = vim.api.nvim_command

-- Auto install packer.nvim if not exists
local install_path = fn.stdpath('data') .. '/site/pack/packer/opt/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end
vim.cmd [[packadd packer.nvim]]
vim.cmd 'autocmd BufWritePost plugins.lua PackerCompile' -- Auto compile when there are changes in plugins.lua

-- Install plugins
require('plugins')
```
</details>

<details>
<summary>lua/plugins.lua</summary>

```lua
local packer = require('packer')
local util = require('packer.util')

packer.init {
    compile_path = util.join_paths(vim.fn.stdpath('config'), 'packer', 'packer_compiled.vim')
}

packer.startup(function(use)
    -- Packer can manage itself as an optional plugin
    use {
        'wbthomason/packer.nvim',
        cond = function()
            return vim.fn.has('nvim-0.5') == 1
        end,
    }
    use {
        'neovim/nvim-lspconfig',
        cond = function()
            return vim.fn.has('nvim-0.5') == 1
        end,
        config = function()
            require 'lsp'
        end,
    }
end)
```
</details>

<details>
<summary>lua/lsp.lua</summary>

```lua
local lsp = require'lspconfig'

lsp.clangd.setup{}
```
</details>

It might be useful to post your `packer_compiled.vim` file here as well, just to check that everything is in order.

**Comment by horseinthesky** [comment] 2021-03-01 15:42
@nanotee I must admit I've completely broken my mind T_T

Your `plugins.lua` works but if I remove all `cond`'s and put `opt`'s instead it stops working.

Here are the files I have tested.
plugins.lua with `cond`
```
local packer = require('packer')
local util = require('packer.util')

packer.init {
    compile_path = util.join_paths(vim.fn.stdpath('config'), 'packer', 'packer_compiled.vim')
}

packer.startup(function(use)
    -- Packer can manage itself as an optional plugin
    use {
        'wbthomason/packer.nvim',
        cond = function()
            return vim.fn.has('nvim-0.5') == 1
        end,
    }
    use {
        'neovim/nvim-lspconfig',
        cond = function()
            return vim.fn.has('nvim-0.5') == 1
        end,
    }
    use {
        'nvim-lua/completion-nvim',
        cond = function()
            return vim.fn.has('nvim-0.5') == 1
        end,
    }
end)
```

`.config/nvim/packer/packer_compiled.vim` for it
```
" Automatically generated packer.nvim plugin loader code

if !has('nvim-0.5')
  echohl WarningMsg
  echom "Invalid Neovim version for packer.nvim!"
  echohl None
  finish
endif

packadd packer.nvim

try

lua << END
local package_path_str = "/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    print('Error running ' .. component .. ' for ' .. name)
    error(result)
  end
  return result
end

_G.packer_plugins = {
  ["completion-nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/completion-nvim"
  },
  ["nvim-lspconfig"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig"
  },
  ["packer.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/packer.nvim"
  }
}

-- Conditional loads
if
  try_loadstring("\27LJ\2\nH\0\0\3\0\4\1\v6\0\0\0009\0\1\0009\0\2\0'\2\3\0B\0\2\2\b\0\0\0X\0\2�+\0\1\0X\1\1�+\0\2\0L\0\2\0\rnvim-0.5\bhas\afn\bvim\2\0", "condition", "packer.nvim")
then
        vim.cmd [[packadd packer.nvim]]
end

if
  try_loadstring("\27LJ\2\nH\0\0\3\0\4\1\v6\0\0\0009\0\1\0009\0\2\0'\2\3\0B\0\2\2\b\0\0\0X\0\2�+\0\1\0X\1\1�+\0\2\0L\0\2\0\rnvim-0.5\bhas\afn\bvim\2\0", "condition", "nvim-lspconfig")
then
        vim.cmd [[packadd nvim-lspconfig]]
end

if
  try_loadstring("\27LJ\2\nH\0\0\3\0\4\1\v6\0\0\0009\0\1\0009\0\2\0'\2\3\0B\0\2\2\b\0\0\0X\0\2�+\0\1\0X\1\1�+\0\2\0L\0\2\0\rnvim-0.5\bhas\afn\bvim\2\0", "condition", "completion-nvim")
then
        vim.cmd [[packadd completion-nvim]]
end

END

catch
  echohl ErrorMsg
  echom "Error in packer_compiled: " .. v:exception
  echom "Please check your config for correctness"
  echohl None
endtry
```


Then plugins.lua with `opt`
```
local packer = require('packer')
local util = require('packer.util')

packer.init {
    compile_path = util.join_paths(vim.fn.stdpath('config'), 'packer', 'packer_compiled.vim')
}

packer.startup(function(use)
    -- Packer can manage itself as an optional plugin
    use {
        'wbthomason/packer.nvim',
        opt = true,
    }
    use {
        'neovim/nvim-lspconfig',
        opt = true,
    }
    use {
        'nvim-lua/completion-nvim',
        opt = true,
    }
end)
```

and `.config/nvim/packer/packer_compiled.vim` for it
```
" Automatically generated packer.nvim plugin loader code

if !has('nvim-0.5')
  echohl WarningMsg
  echom "Invalid Neovim version for packer.nvim!"
  echohl None
  finish
endif

packadd packer.nvim

try

lua << END
local package_path_str = "/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/home/horseinthesky/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    print('Error running ' .. component .. ' for ' .. name)
    error(result)
  end
  return result
end

_G.packer_plugins = {
  ["completion-nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/completion-nvim"
  },
  ["nvim-lspconfig"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig"
  },
  ["packer.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/horseinthesky/.local/share/nvim/site/pack/packer/opt/packer.nvim"
  }
}

END

catch
  echohl ErrorMsg
  echom "Error in packer_compiled: " .. v:exception
  echom "Please check your config for correctness"
  echohl None
endtry
```

**Comment by akinsho** [comment] 2021-03-01 16:39
@horseinthesky from my understanding `opt` plugins are never automatically loaded (to be clear I mean using the key `opt = true` alone without other keys), by specifying a plugin as opt it will be installed but the only way to add those plugins is using `packadd my-plugin-name` the point of being able to do this is that you can for whatever reason you want add in a packadd at some point in your config to load it.

The reason why `cond` works is that although those plugins are also essentially `opt = true`, the packer compiled will be generated with a function to run to check if it should add run `packadd` for you.

I might have missed something in the thread but if your issue is essentially only loading some plugins if they meet a criterial like `has('nvim-0.5')` then you are best off using `cond = <conditions-to-check-nvim-version>` this will install it as `opt` but automatically load it in circumstances where it is true.

**Comment by horseinthesky** [comment] 2021-03-01 17:03
@akinsho Thank you.

My idea was to keep NVIM-0.4 completely unaware of my Lua config. To manage plugins with vim-plug.
And load Lua config only for NVIM-0.5.

Since any NVIM loads anything in `pack/*/start` I cannot install plugins as start plugins.
I was hoping setting every `packer` plugin as `opt` will help me to achieve the goal but clearly I was wrong.

At least this answers my initial question of what exactly is an optional plugin =)

**Comment by akinsho** [comment] 2021-03-01 17:16
@horseinthesky you can still make this work by setting all packer plugins to opt with the same conditional function e.g.
```lua
packer.startup(function(use)
local is_point_five = <condition-here>
 use {"plug-1", cond = is_point_five}
 use {"plug-2", cond = is_point_five}
 use {"plug-3", cond = is_point_five}
 use {"plug-4", cond = is_point_five}
end)
```

Seems kind of complicated to even bother having packer loaded though. When I was in the process of migrating initially I just made all the lua calls conditional and had the vimscript calls in the else branch in my `init.vim` seems a lot less complicated especially since you still have some things installed with `vim-plug`

**Comment by akinsho** [comment] 2021-03-01 17:22
Something like
```vim
"in init.vim
if has('nvim-0.5')
 lua require('mod.setup')
else
 source './vim-setup.vim'
endif
```
That way you don't have to have any conditional logic inside either the vimscript or the lua

**Comment by horseinthesky** [comment] 2021-03-01 17:29
> Something like
> 
> ```viml
> "in init.vim
> if has('nvim-0.5')
>  lua require('mod.setup')
> else
>  source './vim-setup.vim'
> endif
> ```
> 
> That way you don't have to have any conditional logic inside either the vimscript or the lua

This is exactly where I started.
The problem is all plugins (if `mod.setup` is running packer in your case) are loaded from `pack/*/start` whatever NVIM version you run. Thus this if statement makes no sense.

**Comment by akinsho** [comment] 2021-03-01 17:37
Ah sorry I see now, that does sound like a limitation of `packages` I guess one, still slightly messy solution is you could use the `disable` key, rather than `cond`. The difference here is that if the condition is `false` the package is deleted on packer clean. Then maybe you could do something like. Make all plugins disable if not `0.5` like 
```lua
use {"wbthomason/packer.nvim"} -- note this is a start plugin now
use {"plugin", disabled = function()
  return has('nvim-0.5')
end}
```
so if not `0.5` packer clean will remove these plugins then in init.vim
```vim
"in init.vim
if has('nvim-0.5')
 lua require('mod.setup')
else
 exe "PackerClean"
 source './vim-setup.vim'
endif
```
This way packer cleans up before you actually load your vim files. Not particularly clean in my mind but it's either that or all plugins with a `cond` as far as I can see. Alternatively going down the weird strategies route, you could also try removing packer's file from the `&rtp` i.e. not sure if by removing it it will stop the start plugins for packer from being sourced.

**Comment by horseinthesky** [comment] 2021-03-01 18:15
@akinsho I can't say I understand the last one.

I like
```
if has('nvim-0.5')
 lua require 'setup'
else
 source './vim-setup.vim'
endif
```
the most since even `packer` won't be loaded for 0.4 as it is installed as opt plugin.

Therefore 0.4 and 0.5 will be completely separated. The only downside is having `cond` in each plugin setup which in turn is not so nasty I suppose.

Thank you anyway. Need to sleep with all this info to decide if it is too messy or not.

**Comment by akinsho** [comment] 2021-03-01 18:19
Tbh on thinking about it a little more the last option regarding `&runtimepath` wouldn't work anyway so you can just ignore it anyway. Yeah I think condition for all the plugins isn't that big a deal 🤷🏿

**Comment by wbthomason** [comment] 2021-03-03 18:51
Thanks, @akinsho and @nanotee!

@horseinthesky, I'm closing this for now because it seems like things are resolved. Feel free to re-open if you're still having problems!

**Closed by wbthomason** 2021-03-03 18:51 UTC
