### ISSUE TITLE
Update not working in WSL

### ISSUE THREAD

**Issue by tjdevries** [wbthomason/packer.nvim#25] opened 2020-07-26 19:46 UTC
```
|| [packer] Error in coroutine: ...k/packer/opt/packer.nvim/lua/packer/plugin_types/git.lua:203: attempt to index field 'output' (a nil value)
|| [packer] Error in coroutine: ...m/site/pack/packer/opt/packer.nvim/lua/packer/update.lua:70: attempt to index local 'r' (a nil value)
```

I can investigate this some more later, not sure why this is happening.

**Comment by tjdevries** [comment] 2020-07-26 19:46
(but if you have any ideas, that'd be good to know 😆)

**Comment by wbthomason** [comment] 2020-07-27 04:54
Can you give information on the plugin you were trying to install/update when you encountered this?

This is due to a bug with the `merge_output` utility function; it shouldn't be WSL specific, but it indicates that the process of handling checkouts for a plugin encountered errors. It'd be nice to track down why that happens too.

**Comment by wbthomason** [comment] 2020-07-27 05:03
I've fixed the bugs causing the symptoms here in 1bc5337 and a96f5f1, but I'm leaving the issue open for now to see if we can figure out why git is failing here (especially if it turns out to be related to #26).

**Comment by wbthomason** [comment] 2020-07-27 05:05
Also, the only explicit Windows-Linux difference is https://github.com/wbthomason/packer.nvim/blob/a96f5f1ec20b758b27defdec433c664d57d48abe/lua/packer/util.lua#L34-L39.

...now that I think about it, that probably shouldn't require on `jit`, since not all platforms will be using LuaJIT.

**Comment by wbthomason** [comment] 2020-08-03 18:13
(only marked as "can't reproduce" because I personally don't have a WSL environment in which to try and reproduce the issue)

**Comment by bryall** [comment] 2020-08-10 14:56
i am getting this same error on Ubuntu when calling PackerUpdate. PackerInstall works as intended for me. 

just starting to get into lua, is there an easy way to debug this to give more info?

**Comment by bryall** [comment] 2020-08-10 15:17
I was using git version 2.17.1, just upgraded to latest version 2.24 and did not get this error after upgrading. So I think this is a git version problem

**Comment by wbthomason** [comment] 2020-08-10 16:12
@bryall Ah, that's good to know, thanks! I don't suppose you captured the error output from running `PackerUpdate`? I suspect the culprit will be one of the arguments to the commands `packer` uses to get the commits pulled in an update - something added after 2.17.1

**Comment by bryall** [comment] 2020-08-10 16:21
it was the same error as @tjdevries in the original. the line number for git.lua was 206 and the the line number was the same for update.lua

**Comment by wbthomason** [comment] 2020-08-10 16:57
Hmm, ok. I might have to try spinning up Ubuntu in a Docker container or something to replicate the error; I'm not seeing anything obvious that would cause this just from inspection. I've added a change

**Comment by gagbo** [comment] 2020-09-18 08:24
Same error still in git.lua, also running git 2.17.1 on Ubuntu

**Comment by wbthomason** [comment] 2020-09-18 19:29
@gagbo On the latest `packer` commit? There have been some fixes to the way `packer` works on Windows since the last activity on this issue.

**Comment by wbthomason** [comment] 2020-09-18 19:32
@gagbo The error is still on line 206 in `git.lua`?

**Comment by gagbo** [comment] 2020-09-18 21:30
yes it is, and I was testing on Bionic Beaver (18.04)

The weird thing is that it worked at least once (but I don't remember when or how) since my packer path is populated

**Comment by gagbo** [comment] 2020-09-18 21:32
Sorry it's line 212 I'll edit

**Comment by wbthomason** [comment] 2020-09-21 15:27
Hmm. I still do not understand why this is happening, but I added a `nil` check to the function being called there, which will hopefully fix the problem. Please reopen if you're still seeing the error messages (or any others).

Thanks!

**Closed** 2020-09-21 15:27 UTC
Labels: bug, can't reproduce, help wanted

**Comment by gagbo** [comment] 2020-09-21 16:59
The new display thing was actually more helpful, I'll open another issue I think

**Comment by gagbo** [comment] 2020-09-21 17:04
Linking for the record #52
