### ISSUE TITLE
Packer needs to fetch before checking out to a new commit

### ISSUE THREAD

**Issue by stasjok** [wbthomason/packer.nvim#558] opened 2021-08-18 07:30 UTC
- `nvim --version`: v0.5.0
- `git --version`: 2.31.1
- Operating system/version: Debian 10
- Terminal name/version: WT 1.9

### Steps to reproduce
* Install some git-repository pinned to a latest commit.
* Push some commits to plugin repository (or wait)
* Change `commit` parameter in plugin specification to the new latest commit
* Try `:PackerSync` command

### Actual behaviour
I get an error: `fatal: reference is not a tree: 344b0d93f2e208094f01790d59ec670ec0cae6e1`.
But if I manually cd to the plugin directory and run `git fetch`, then `:PackerSync` is working.

### Expected behaviour
Packer should correctly fetch latest commits before checking out to new specified commit.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

```lua
packer.startup({
  {
    { "L3MON4D3/LuaSnip", commit = "344b0d93f2e208094f01790d59ec670ec0cae6e1" },
  }
})
```
</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by JoseConseco** [comment] 2021-08-24 09:52
maybe its not 100% related but I have  error when I PackerSync() on plugins that are using  branch option. Failed to update or something like that. But If I run: git fetch on plugin repo, then PackerSync() will correctly  update and checkout selected branch.
So +1 for auto fetch eg. when branch option is used.

**Comment by wbthomason** [comment] 2021-09-01 22:46
Thanks for your report, and sorry for my delayed response. This sounds like a regression, since these features have worked as expected for me in previous testing.

**Comment by wbthomason** [comment] 2021-09-01 22:58
Ok - it looks like some of the `git` logic got shifted around at one point, so we're skipping the necessary `fetch` operation. The `git` module honestly needs a comprehensive rework, but I should be able to hack in a fix for this in the meanwhile.

**Closed** 2021-09-04 03:11 UTC
Labels: bug
