### ISSUE TITLE
Special character Symbol confused as escape sequence

### ISSUE THREAD

**Issue by pannet1** [wbthomason/packer.nvim#1088] opened 2022-10-10 16:09 UTC
https://github.com/lewis6991/gitsigns.nvim/issues/649

Post the contents of ~/.cache/nvim/packer.nvim.log here
nuked the log file prior running minimum config
nothing is logged.

<details>
Error detected while processing /home/pannet1/minimal.lua:
E5112: Error while creating lua chunk: /home/pannet1
/minimal.lua:19: invalid escape sequence near '''
Press ENTER or type command to continue
</details>

**Comment by stutonk** [comment] 2022-11-26 17:34
I also had this issue after a recent update. The actual error seems to be caused by something in a different package (in this case [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)). The downstream package has been fixed with release tag `v0.5` but calling `:PackerUpdate` wasn't fixing the problem. Turns out, I had pinned a specific commit in my config. So make sure if you're pinned to a specific commit that it's at least [d7e0bcbe45bd9d5d106a7b2e11dc15917d272c7a](https://github.com/lewis6991/gitsigns.nvim/commit/d7e0bcbe45bd9d5d106a7b2e11dc15917d272c7a) for this specific package

**Closed** 2022-11-28 15:00 UTC
Labels: bug, can't reproduce
