### ISSUE TITLE
Crashes with path with spaces in its installation directory

### ISSUE THREAD

**Issue by sam20908** [wbthomason/packer.nvim#287] opened 2021-04-12 22:32 UTC
When Packer tries to install itself into a path with spaces, it fails because It doesn't handle it.

![image](https://user-images.githubusercontent.com/18388795/114470726-38834180-9ba4-11eb-9f13-6838468882b6.png)

This also applies to installing **anything** too, even if I manually cloned packer to the right directory.

![image](https://user-images.githubusercontent.com/18388795/114470861-708a8480-9ba4-11eb-855c-3331093253e3.png)

**Comment by wbthomason** [comment] 2021-04-13 03:19
Thanks for the report!

Your first problem (with cloning `packer`) is just how spaces in paths are handled by `git` and most CLI tools - you need to manually escape them. `packer` does not, in general, clone itself (I assume this is from a bootstrap function?)

The second problem is related to the stalled PR #166. Could you please give that a try (I just rebased it onto current `master`) and confirm that it does not solve the problem for you? Assuming it doesn't, could you please post the contents of `stdpath('cache')\packer.nvim.log`?

**Comment by sam20908** [comment] 2021-04-14 04:24
Confirmed that #291 does fix the first issue. I'll test the second issue tomorrow.

**Comment by sam20908** [comment] 2021-04-15 00:41
Confirmed that #166 does work as well.

**Comment by sam20908** [comment] 2021-04-16 01:22
> Confirmed that #166 does work as well.

It does *partially* work, but I get this:
![image](https://user-images.githubusercontent.com/18388795/114958215-79cf5780-9e17-11eb-85f3-ac9d08f5cd7c.png)

**Comment by sam20908** [comment] 2021-04-16 04:16
I can confirm that #166 doesn't work on Windows with space in path.

**Comment by sam20908** [comment] 2021-04-16 04:52
I think we need to use `system` to invoke cloning, similar to #291.

**Comment by nanotee** [comment] 2021-04-16 13:33
That's odd, the error code is `E739`, which according to the Vim documentation is caused by `vim.fn.mkdir()`, but on my Linux system the function handles spaces just fine. I'll have to test this on Windows

**Comment by wbthomason** [comment] 2021-04-16 14:08
> I think we need to use `system` to invoke cloning, similar to #291.

@sam20908 `system` is blocking, so it's not an option. Using the `luv` spawn API, as we do, should be fine with proper string escaping.

Given that `fnameescape` is a built-in function, could you test if it works as expected for escaping when used manually on Windows?

**Comment by sam20908** [comment] 2021-04-16 14:35
> That's odd, the error code is `E739`, which according to the Vim documentation is caused by `vim.fn.mkdir()`, but on my Linux system the function handles spaces just fine. I'll have to test this on Windows

I guess I can't reproduce the situation anymore... Probably because I updated Neovim to latest beta, sorry!

That situation was caused by deleting some specific directory inside of `install_path` and then attempting to clone. I guess Neovim fixed the issue in the update 😄 .

However, #166 still doesn't work on Windows, and I have checked the install command it produces, but it looks fine...

**Comment by nanotee** [comment] 2021-04-16 16:24
> Given that `fnameescape` is a built-in function, could you test if it works as expected for escaping when used manually on Windows?

Just tested this on Windows: `:echo fnameescape('C:\Users\FooBar\test file with spaces')` returns `'C:\Users\FooBar\test\ file\ with\ spaces'` which is... not good, given that `\` is a path separator and not an escape character.

Apparently, `fnameescape()` doesn't work very well on Windows: https://github.com/vim/vim/issues/541

**Comment by sam20908** [comment] 2021-04-16 21:29
> I guess I can't reproduce the situation anymore... Probably because I updated Neovim to latest beta, sorry!

Never mind, I was not on #166. It also explains why "operation not permitted" error occurred.

Do we have to manually escape the path in the while being?

**Comment by sam20908** [comment] 2021-07-03 13:48
Sorry to ping, but has any progress made on this?

**Comment by nanotee** [comment] 2021-07-03 14:19
@sam20908 Could you try #439 and see if it fixes the issue?

**Comment by sam20908** [comment] 2021-07-03 17:32
> @sam20908 Could you try #439 and see if it fixes the issue?

I can confirm that it downloads the packages successfully but something weird is happening at the end...

```
 Failed to install glepnir\galaxyline.nvim
  Errors:
    Cloning into 'C:\Users\Sam Huang\AppData\Local\nvim-data\site\pack\packer\start\galaxyline.nvim'...
    remote: Enumerating objects: 55, done.        
    remote: Counting objects:   1% (1/55)        
    remote: Counting objects:   3% (2/55)        
    remote: Counting objects:   5% (3/55)
    remote: Counting objects:   7% (4/55)        
    remote: Counting objects:   9% (5/55)        
    remote: Counting objects:  10% (6/55)        
    remote: Counting objects:  12% (7/55)        
    remote: Counting objects:  14% (8/55)        
    remote: Counting objects:  16% (9/55)        
    remote: Counting objects:  18% (10/55)        
    remote: Counting objects:  20% (11/55)        
    remote: Counting objects:  21% (12/55)        
    remote: Counting objects:  23% (13/55)        
    remote: Counting objects:  25% (14/55)        
    remote: Counting objects:  27% (15/55)        
    remote: Counting objects:  29% (16/55)        
    remote: Counting objects:  30% (17/55)        
    remote: Counting objects:  32% (18/55)        
    remote: Counting objects:  34% (19/55)        
    remote: Counting objects:  36% (20/55)        
    remote: Counting objects:  38% (21/55)        
    remote: Counting objects:  40% (22/55)        
    remote: Counting objects:  41% (23/55)        
    remote: Counting objects:  43% (24/55)        
    remote: Counting objects:  45% (25/55)        
    remote: Counting objects:  47% (26/55)        
    remote: Counting objects:  49% (27/55)        
    remote: Counting objects:  50% (28/55)        
    remote: Counting objects:  52% (29/55)        
    remote: Counting objects:  54% (30/55)        
    remote: Counting objects:  56% (31/55)        
    remote: Counting objects:  58% (32/55)        
    remote: Counting objects:  60% (33/55)        
    remote: Counting objects:  61% (34/55)        
    remote: Counting objects:  63% (35/55)        
    remote: Counting objects:  65% (36/55)        
    remote: Counting objects:  67% (37/55)        
    remote: Counting objects:  69% (38/55)        
    remote: Counting objects:  70% (39/55)        
    remote: Counting objects:  72% (40/55)        
    remote: Counting objects:  74% (41/55)        
    remote: Counting objects:  76% (42/55)        
    remote: Counting objects:  78% (43/55)        
    remote: Counting objects:  80% (44/55)        
    remote: Counting objects:  81% (45/55)        
    remote: Counting objects:  83% (46/55)        
    remote: Counting objects:  85% (47/55)        
    remote: Counting objects:  87% (48/55)        
    remote: Counting objects:  89% (49/55)        
    remote: Counting objects:  90% (50/55)        
    remote: Counting objects:  92% (51/55)        
    remote: Counting objects:  94% (52/55)        
    remote: Counting objects:  96% (53/55)        
    remote: Counting objects:  98% (54/55)        
    remote: Counting objects: 100% (55/55)        
    remote: Counting objects: 100% (55/55), done.        
    remote: Compressing objects:   1% (1/51)        
    remote: Compressing objects:   3% (2/51)        
    remote: Compressing objects:   5% (3/51)        
    remote: Compressing objects:   7% (4/51)        
    remote: Compressing objects:   9% (5/51)        
    remote: Compressing objects:  11% (6/51)        
    remote: Compressing objects:  13% (7/51)        
    remote: Compressing objects:  15% (8/51)        
    remote: Compressing objects:  17% (9/51)        
    remote: Compressing objects:  19% (10/51)        
    remote: Compressing objects:  21% (11/51)        
    remote: Compressing objects:  23% (12/51)        
    remote: Compressing objects:  25% (13/51)        
    remote: Compressing objects:  27% (14/51)        
    remote: Compressing objects:  29% (15/51)        
    remote: Compressing objects:  31% (16/51)
    remote: Compressing objects:  33% (17/51)        
remote: Compressing objects:  35% (18/51)        
remote: Compressing objects:  37% (19/51)        
remote: Compressing objects:  39% (20/51)        
remote: Compressing objects:  41% (21/51)        
remote: Compressing objects:  43% (22/51)        
remote: Compressing objects:  45% (23/51)        
remote: Compressing objects:  47% (24/51)        
remote: Compressing objects:  49% (25/51)        
remote: Compressing objects:  50% (26/51)        
remote: Compressing objects:  52% (27/51)        
remote: Compressing objects:  54% (28/51)        
remote: Compressing objects:  56% (29/51)        
remote: Compressing objects:  58% (30/51)
    remote: Compressing objects:  60% (31/51)        
remote: Compressing objects:  62% (32/51)        
remote: Compressing objects:  64% (33/51)        
remote: Compressing objects:  66% (34/51)        
remote: Compressing objects:  68% (35/51)        
remote: Compressing objects:  70% (36/51)        
remote: Compressing objects:  72% (37/51)        
remote: Compressing objects:  74% (38/51)        
remote: Compressing objects:  76% (39/51)        
remote: Compressing objects:  78% (40/51)        
remote: Compressing objects:  80% (41/51)        
remote: Compressing objects:  82% (42/51)        
remote: Compressing objects:  84% (43/51)        
remote: Compressing objects:  86% (44/51)        
remote: Compressing objects:  88% (45/51)        
remote: Compressing objects:  90% (46/51)        
remote: Compressing objects:  92% (47/51)        
remote: Compressing objects:  94% (48/51)        
remote: Compressing objects:  96% (49/51)        
remote: Compressing objects:  98% (50/51)        
remote: Compressing objects: 100% (51/51)        
remote: Compressing objects: 100% (51/51), done.
    Receiving objects:   1% (1/55)
Receiving objects:   3% (2/55)
    Receiving objects:   5% (3/55)
Receiving objects:   7% (4/55)
Receiving objects:   9% (5/55)
Receiving objects:  10% (6/55)
Receiving objects:  12% (7/55)
    Receiving objects:  14% (8/55)
Receiving objects:  16% (9/55)
Receiving objects:  18% (10/55)
    Receiving objects:  20% (11/55)
    Receiving objects:  21% (12/55)
Receiving objects:  23% (13/55)
Receiving objects:  25% (14/55)
Receiving objects:  27% (15/55)
Receiving objects:  29% (16/55)
    Receiving objects:  30% (17/55)
Receiving objects:  32% (18/55)
Receiving objects:  34% (19/55)
Receiving objects:  36% (20/55)
Receiving objects:  38% (21/55)
    Receiving objects:  40% (22/55)
Receiving objects:  41% (23/55)
    Receiving objects:  43% (24/55)
    Receiving objects:  45% (25/55)
remote: Total 55 (delta 17), reused 19 (delta 0), pack-reused 0
    Receiving objects:  47% (26/55)
Receiving objects:  49% (27/55)
    Receiving objects:  50% (28/55)
Receiving objects:  52% (29/55)
Receiving objects:  54% (30/55)
Receiving objects:  56% (31/55)
    Receiving objects:  58% (32/55)
    Receiving objects:  60% (33/55)
Receiving objects:  61% (34/55)
Receiving objects:  63% (35/55)
Receiving objects:  65% (36/55)
Receiving objects:  67% (37/55)
Receiving objects:  69% (38/55)
Receiving objects:  70% (39/55)
Receiving objects:  72% (40/55)
Receiving objects:  74% (41/55)
Receiving objects:  76% (42/55)
Receiving objects:  78% (43/55)
Receiving objects:  80% (44/55)
Receiving objects:  81% (45/55)
    Receiving objects:  83% (46/55)
Receiving objects:  85% (47/55)
Receiving objects:  87% (48/55)
    Receiving objects:  89% (49/55)
Receiving objects:  90% (50/55)
Receiving objects:  92% (51/55)
    Receiving objects:  94% (52/55)
Receiving objects:  96% (53/55)
Receiving objects:  98% (54/55)
Receiving objects: 100% (55/55)
    Receiving objects: 100% (55/55), 26.25 KiB | 5.25 MiB/s, done.
    Resolving deltas:   0% (0/17)
    Resolving deltas:   5% (1/17)
Resolving deltas:  11% (2/17)
    Resolving deltas:  17% (3/17)
Resolving deltas:  23% (4/17)
Resolving deltas:  29% (5/17)
    Resolving deltas:  35% (6/17)
Resolving deltas:  41% (7/17)
Resolving deltas:  47% (8/17)
Resolving deltas:  52% (9/17)
Resolving deltas:  58% (10/17)
Resolving deltas:  64% (11/17)
Resolving deltas:  70% (12/17)
Resolving deltas:  76% (13/17)
    Resolving deltas:  82% (14/17)
Resolving deltas:  88% (15/17)
Resolving deltas:  94% (16/17)
    Resolving deltas: 100% (17/17)
    Resolving deltas: 100% (17/17), done.
    git: 'Huang\AppData\Local\nvim-data\site\pack\packer\start\galaxyline.nvim' is not a git command. See 'git --help'.
```

That was for all the packages

**Comment by sam20908** [comment] 2021-07-03 17:34
Same with updating packages

```
✗ Failed to update nvim-telescope\telescope.nvim
  Errors:
    git: 'Huang\AppData\Local\nvim-data\site\pack\packer\start\telescope.nvim' is not a git command. See 'git --help'.
    git: 'Huang\AppData\Local\nvim-data\site\pack\packer\start\telescope.nvim' is not a git command. See 'git --help'.
    git: 'Huang\AppData\Local\nvim-data\site\pack\packer\start\telescope.nvim' is not a git command. See 'git --help'.
```

**Comment by nanotee** [comment] 2021-07-03 17:50
Thanks for testing! Yeah, I expected updating to fail. I'm guessing you have `branch = 'main'` in your `galaxyline` specification?

#303 is supposed to fix the other git commands (it might have been better to make one big PR, but I thought a separate, smaller one would be easier to merge)

**Comment by sam20908** [comment] 2021-07-03 17:55
@nanotee No I don't have `branch = 'main' on `galaxyline` although I do have it In other packages.

Also I tested #303 and it works.

**Comment by wbthomason** [comment] 2021-07-04 00:08
Sorry, I completely lost track of this + #303 + #439. Totally my bad. Taking a look at those now, which will hopefully help this.

**Comment by wbthomason** [comment] 2021-07-06 16:19
#303 and #439 have been merged, so I think we can consider this closed? Feel free to reopen if you're still seeing the error.

**Closed by wbthomason** 2021-07-06 16:19 UTC
