### ISSUE TITLE
Packer hangs when setting a maximum number of simultaneous jobs

### ISSUE THREAD

**Issue by nanotee** [wbthomason/packer.nvim#57] opened 2020-09-26 21:21 UTC
I am using the `init` function to limit the number of jobs, but it doesn't seem to work. Here's an approximation of what my config looks like:

```lua
vim.cmd 'packadd! packer.nvim'

local packer = require('packer')

packer.init {
    max_jobs = 5,
}

packer.startup(function(use)
    use 'user/plugin1'
    use 'user/plugin2'
    use 'user/plugin3'
    use 'user/plugin4'
    use 'user/plugin5'
    use 'user/plugin6'
    use 'user/plugin7'
    use 'user/plugin8'
    use 'user/plugin9'
    use 'user/plugin10'
end)
```

When I run `:PackerUpdate`, Packer outputs something like this:

```
            packer.nvim - updating 5 / 10 plugins            
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
 ✓ user/plugin1: already up to date
 ✓ user/plugin2: already up to date
 ✓ user/plugin3: already up to date
 ✓ user/plugin4: already up to date
 ✓ user/plugin5: already up to date
```

It never actually reaches the end screen and waits indefinitely. I can still move my cursor and quit Neovim just fine.

I may be doing something wrong, but I don't know what

**Comment by wbthomason** [comment] 2020-09-28 13:45
Thanks for the report! This is a regression; I'll try to track down what commit caused it.

**Comment by wbthomason** [comment] 2020-09-28 14:50
Ah, this is a bug introduced with interruptible tasks. It's actually present without the `max_jobs` restriction too, but doesn't show up because every job that needs to run is started at the beginning of the update stage.

**Comment by wbthomason** [comment] 2020-09-28 15:39
This should be fixed now! @nanotee please let me know if you continue to experience the buggy behavior!

**Closed** 2020-09-28 15:39 UTC
Labels: bug
