### ISSUE TITLE
add key `defer [N]` to lazy-load plugin after N seconds of idle time

### ISSUE THREAD

**Issue by younger-1** [wbthomason/packer.nvim#1051] opened 2022-09-05 16:59 UTC
### Describe the feature

Like https://github.com/jwiegley/use-package#defer-now-accepts-an-optional-numeric-argument

**Comment by younger-1** [comment] 2022-09-05 17:13
related: #8

**Comment by akinsho** [comment] 2022-09-05 17:18
@younger-1 this seems like a duplicate of the issue you linked, don't think we need both, maybe you can add your link to that issue.

**Comment by wbthomason** [comment] 2022-09-05 18:06
Closing as duplicate. If you're interested in helping with a PR, @younger-1, this should be an approachable feature (unless `packadd` can't be used in callbacks).

**Closed by wbthomason** 2022-09-05 18:06 UTC
Labels: enhancement
