### ISSUE TITLE
use { config = } doesn't work with nvim 0.5.0

### ISSUE THREAD

**Issue by cryptomilk** [wbthomason/packer.nvim#452] opened 2021-07-06 10:20 UTC
The config loading of `use` doesn't seem to work with neovim 0.5.0.

- `nvim --version`: v0.5.0
- `git --version`: 2.32.0
- Operating system/version: openSUSE Tumbleweed
- Terminal name/version: konsole 21.04.2/tmux 3.2

## Steps to reproduce

In plugins.lua I have:

```lua
    use {
        "npxbr/gruvbox.nvim",
        requires = {"rktjmp/lush.nvim"},
        config = "require('plugins.gruvbox')",
    }
```

My `plugins/gruvbox.lua`:

```lua
vim.g.gruvbox_contrast_dark      = 'medium'
vim.g.gruvbox_contrast_light     = 'hard'
vim.g.gruvbox_italic             = 0
vim.g.gruvbox_italicize_comments = 0
vim.g.gruvbox_italicize_strings  = 0
vim.g.gruvbox_improved_strings   = 1
vim.g.gruvbox_improved_warnings  = 1

pcall(vim.cmd, [[colorscheme gruvbox]])
```

### Actual behaviour
The plugins/gruvbox.lua isn't loaded the theme is not applied. It works if I call it manually

`:lua require('plugins.gruvbox')`

### Expected behaviour
The theme should be applied.

Can I provide mode debug information somehow?

**Comment by gegoune** [comment] 2021-07-06 10:24
Your gruvbox.lua should be returning function, as `config` takes a function or single command string if I am not mistaken.

**Comment by cryptomilk** [comment] 2021-07-06 10:39
```lua
    use {
        "npxbr/gruvbox.nvim",
        requires = {"rktjmp/lush.nvim"},
        --config = "require('plugins.gruvbox')",
        config = function()
            vim.g.gruvbox_contrast_dark      = 'medium'
            vim.g.gruvbox_contrast_light     = 'hard'
            vim.g.gruvbox_italic             = 0
            vim.g.gruvbox_italicize_comments = 0
            vim.g.gruvbox_italicize_strings  = 0
            vim.g.gruvbox_improved_strings   = 1
            vim.g.gruvbox_improved_warnings  = 1

            pcall(vim.cmd, [[colorscheme gruvbox]])
        end,
    }
```

Doesn't work either ...

**Comment by akinsho** [comment] 2021-07-06 10:53
@cryptomilk I think this is a duplicate of #266. I don't think setting your colorscheme inside of a packer config block is a good idea/doesn't work. It is best to load your colorscheme in your init.lua since vim packages which packer uses don't get loaded till later than is often expected.

I don't think this issue is actually that `config` blocks dont work since I think we'd be seeing many more complaints if that were the case. Testing locally also on 0.5 and I'm pretty confident config blocks are working.

**Closed** 2021-07-06 11:29 UTC
Labels: bug
