### ISSUE TITLE
On lazy loading - Error after PackerSync/PackerCompile - Not an editor command

### ISSUE THREAD

**Issue by TheBlob42** [wbthomason/packer.nvim#576] opened 2021-08-26 12:09 UTC
- `nvim --version`: NVIM v0.5.0
- `git --version`: git version 2.30.2
- Operating system/version: Pop!_OS 21.04
- Terminal name/version: kitty 0.23.1

This issue is exactly like #442 and was fixed in the meantime by #449, but it seems that this issue was "reintroduced" lately 

### Steps to reproduce

> Checkout the minimal `init.lua` to reproduce this exactly

- open NVIM
- run `:PackerSync`
- run `:NvimTreeToggle`
- run `:PackerCompile`
- run `:NvimTreeToggle`

### Actual behaviour

```text
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:82: Vim:E492: Not an
 editor command: NvimTreeToggle 
Please check your config for correctness
```

### Expected behaviour

NvimTree toggles (in this case it should close again) without any error

### packer files

<details>
<summary>Minimal init.lua to reproduce</summary>

```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
local is_packer_installed = vim.fn.isdirectory(install_path) == 1
if not is_packer_installed then
    vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end

require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use { 'kyazdani42/nvim-tree.lua', cmd = 'NvimTreeToggle' }
end)
```

</details>

<details>
<summary>packer compiled file</summary>

-- Automatically generated packer.nvim plugin loader code

if vim.api.nvim_call_function('has', {'nvim-0.5'}) ~= 1 then
  vim.api.nvim_command('echohl WarningMsg | echom "Invalid Neovim version for packer.nvim! | echohl None"')
  return
end

vim.api.nvim_command('packadd packer.nvim')

local no_errors, error_msg = pcall(function()

  local time
  local profile_info
  local should_profile = false
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/home/tobi/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/tobi/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/tobi/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/tobi/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/home/tobi/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ["nvim-tree.lua"] = {
    commands = { "NvimTreeToggle" },
    loaded = false,
    needs_bufread = false,
    path = "/home/tobi/.local/share/nvim/site/pack/packer/opt/nvim-tree.lua"
  },
  ["packer.nvim"] = {
    loaded = true,
    path = "/home/tobi/.local/share/nvim/site/pack/packer/start/packer.nvim"
  }
}

time([[Defining packer_plugins]], false)

-- Command lazy-loads
time([[Defining lazy-load commands]], true)
pcall(vim.cmd, [[command! -nargs=* -range -bang -complete=file NvimTreeToggle lua require("packer.load")({'nvim-tree.lua'}, { cmd = "NvimTreeToggle", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]])
time([[Defining lazy-load commands]], false)

if should_profile then save_profiles() end

end)

if not no_errors then
  vim.api.nvim_command('echohl ErrorMsg | echom "Error in packer_compiled: '..error_msg..'" | echom "Please check your config for correctness" | echohl None')
end

</details>

**Comment by rafamadriz** [comment] 2021-08-29 15:39
Yes, I can confirm, the issue was introduced again. I noticed this like a week ago. As @TheBlob42 said, it's basically what I described in #442

**Comment by wbthomason** [comment] 2021-08-30 20:00
Maybe #470 re-broke this? Though that's been merged for ~19 days, it's the only recently merged PR that should've affected commands, to my knowledge.

**Comment by rafamadriz** [comment] 2021-08-30 21:58
> Maybe #470 re-broke this? Though that's been merged for ~19 days, it's the only recently merged PR that should've affected commands, to my knowledge.

okay @wbthomason  I just tested and you're right, before commit 9de97ca891972834a3e3ef66e7fd069c8d4fa309 it's all working fine.

**Comment by wbthomason** [comment] 2021-08-30 22:08
Yeah, it looks like that commit accidentally overwrote the changes of #449. I'll push a fix commit shortly.

**Comment by wbthomason** [comment] 2021-08-30 23:05
Please reopen if my fix did not address this problem!

**Closed** 2021-08-30 23:05 UTC
Labels: bug

**Comment by TheBlob42** [comment] 2021-09-01 15:52
Sorry for my late reply. Since your fix the problem did not occur to me anymore, therefore I would consider this fixed :slightly_smiling_face:
