### ISSUE TITLE
sourcehut hosted package gets autoremoved

### ISSUE THREAD

**Issue by xenrox** [wbthomason/packer.nvim#378] opened 2021-05-26 20:50 UTC
- `nvim --version`: NVIM v0.5.0-dev+1356-g0b905be47
- `git --version`: git version 2.31.1
- Operating system/version: Arch Linux
- Terminal name/version: kitty 0.20.3

### Steps to reproduce
Add a plugin hosted on sourcehut.

### Actual behaviour
Calling `PackerSync` causes packer to want to remove the package (as if I removed it from my plugin file) and download it again. This didn't happen on packer two days ago.

### Expected behaviour
Just update the plugin or do nothing

### packer files
` use {'https://git.xenrox.net/~xenrox/debug-packer'}`
Packer log
https://paste.xenrox.net/~xenrox/fbe3ba404ccdc13724f05597252e6a72b4e264ca

packer compiled file
https://paste.xenrox.net/~xenrox/2f9f632bf1bfdd33d620fea3eeaff6327157ecd4

**Comment by wbthomason** [comment] 2021-05-26 21:21
Thanks for the report, and sorry for the regression. This is another issue due to #374; I can put out a fix tonight.

**Comment by wbthomason** [comment] 2021-05-26 21:36
It looks like this is happening because we use the full URL for the plugin name, so the `repo_name` comparison is always different (in `find_missing_plugins`). This happens for full URLs on Github too.

@akinsho Did full URLs work with #340? As in, is this a regression due to the changes added in #374 to address the SSH URL problem?

**Comment by wbthomason** [comment] 2021-05-26 21:59
@xenrox @uyha could you please test out #378?

**Comment by xenrox** [comment] 2021-05-26 22:11
Fixes the bug for me.
Thanks a lot!

**Comment by uyha** [comment] 2021-05-26 22:23
I still have the same problem after applying the patch. I think it's because of Windows' using backslash instead of forward slash for path.

**Comment by mjlbach** [comment] 2021-05-26 22:23
I'm having a very similar issue to OP with 'hkupty/iron.nvim.git'

**Comment by wbthomason** [comment] 2021-05-26 22:29
@mjlbach: is that the full URL you specify a plugin with?

@uyha: I would think that the different separator shouldn't matter, since these should just be URLs which use the same separator on all OSes. Do you have a concrete example that leads you to suspect this?

**Comment by xenrox** [comment] 2021-05-26 22:30
> 'hkupty/iron.nvim.git'

Gets fixed by using 'hkupty/iron.nvim'

**Comment by mjlbach** [comment] 2021-05-26 22:35
> Gets fixed by using 'hkupty/iron.nvim'

Ah, thanks :)

**Comment by uyha** [comment] 2021-05-26 22:41
Just to make sure I did everything correctly, this is the directory `packer.nvim` when i'm testing your patch.
![image](https://user-images.githubusercontent.com/8091245/119739984-62a66f80-be83-11eb-84be-a369bedcc248.png)

One of my plugin is this `use {'neovim/nvim-lspconfig'}`, so when I run `:PackerSync`, it will ask to remove all the plugins and reinstall them. After finished reinstalling, the message printout like this 
![image](https://user-images.githubusercontent.com/8091245/119740464-3f2ff480-be84-11eb-81dd-7fa4c13beb9a.png). That's why I think it may be a back/forward slash problem on Windows.

**Comment by wbthomason** [comment] 2021-05-26 22:57
@uyha Fascinating, thanks. I agree that it seems like something incorrect is happening with separators, related to but distinct from the issue @xenrox reported. I'll merge the PR fixing that and then see if I can figure out the Windows issue; in the meanwhile, pinning to a commit before #340 was merged should restore `packer` to working order on Windows for you, as a workaround.

**Closed** 2021-05-26 22:57 UTC
Labels: bug

**Comment by akinsho** [comment] 2021-05-27 08:29
@wbthomason (as you might have already found) this would have been as much of an issue in #340 as it was in #374 I had assumed that the structure of plugin names was `author/repo` rather than expecting a url.
