### ISSUE TITLE
Error running config for packer.nvim: [string "..."]:0: attempt to call upvalue '' (a nil value)

### ISSUE THREAD

**Issue by TobTobXX** [wbthomason/packer.nvim#1001] opened 2022-08-05 14:23 UTC
- `nvim --version`: NVIM v0.7.2
- `git --version`: git version 2.37.1
- Operating system/version: Arch Linux
- Terminal name/version: foot version: 1.12.1

### Steps to reproduce
Install packer and use this init.lua:
```
local function nnoremap (lhs, rhs)
	vim.keymap.set('n', lhs, rhs, { noremap = true });
end

require'packer'.init();

require'packer'.use {
	'https://github.com/wbthomason/packer.nvim',
	config = function()
		nnoremap('<Leader>ps', '<cmd>PackerSync<cr>');
	end,
};
```
### Actual behaviour
I get this error: ` Error running config for packer.nvim: [string "..."]:0: attempt to call upvalue '' (a nil value)`

### Expected behaviour
No error? The local function should be captured like any other variable.

**Comment by akinsho** [comment] 2022-08-05 14:52
This is a duplicate of #351 please read through there for a solution or forward any comments there.

**Comment by akinsho** [comment] 2022-08-05 14:53
https://github.com/wbthomason/packer.nvim/issues/996 has a clearer explanation/solution

**Closed by akinsho** 2022-08-05 14:52 UTC
Labels: bug

**Comment by TobTobXX** [comment] 2022-08-05 15:57
Thank you and sorry for duplicating.

For anyone that arrives here through a search, a TL;DR:
You can't use upvalues (ie. values that get captured by an anonymous function) in the config function. Attach it to the global object and access it through there. This is actually documented [in the README](https://github.com/wbthomason/packer.nvim#compiling-lazy-loaders).

This is what worked for me:

Old:
```lua
local function nnoremap (lhs, rhs)
	vim.keymap.set('n', lhs, rhs, { noremap = true });
end

require'packer'.init();

require'packer'.use {
	'https://github.com/wbthomason/packer.nvim',
	config = function()
		nnoremap('<Leader>ps', '<cmd>PackerSync<cr>');
	end,
};
```
New:
```lua
local function nnoremap (lhs, rhs)
	vim.keymap.set('n', lhs, rhs, { noremap = true });
end
_G.map_fns = {
	nnoremap = nnoremap,
};

require'packer'.init();

require'packer'.use {
	'https://github.com/wbthomason/packer.nvim',
	config = function()
		map_fns.nnoremap('<Leader>ps', '<cmd>PackerSync<cr>');
	end,
};
```

*I'm not a Lua pro. Take it with a grain of salt.
