### ISSUE TITLE
Latest commit appears to have broken Windows support

### ISSUE THREAD

**Issue by samr** [wbthomason/packer.nvim#819] opened 2022-02-13 21:55 UTC
- `nvim --version`:  v0.7.0-dev+1075-g6f5fae08a
- `git --version`: git version 2.32.0.windows.2
- Operating system/version: Windows 10 21H1
- Terminal name/version: Windows terminal with Git Bash

### Steps to reproduce
Check out latest commit: 75d70d454a852afd92d0f9272d286558ba532954
Run `:PackerSync` on Windows
Watch all plugins get removed and reinstalled every time the above sync is run (including packer.nvim)

### packer files

<details>
<summary>Plugin specification file(s)</summary>

I can reproduce this with just the packer plugin specified and no other plugins.

</details>

Note that I can fix all of this by going back one commit.
```
use {
    "wbthomason/packer.nvim",
    event = "VimEnter",
    commit = "c5e98e3ca84843dbae47cd8f3a76bc38c6404241",
}
```

**Comment by TheLeoP** [comment] 2022-02-13 23:40
I can reproduce the bug, it happens because of line 193 of packer.lua in the latest commit.

```lua
local segment_separator = plugin_spec.type == plugin_utils.local_plugin_type and util.get_separator() or '/'
local name_segments = vim.split(path, segment_separator)
```

Saving the values on a table and printing them for debugging gives me the following output:


```
{
  plugin_spec_type = 'git',
  plugin_utils_local_plugin_type = 'local',
  util_separator = '\\'
}
```

The next picture shows this beeing the case for every plugin. And, since line 194 uses `/` as separator if the comparison fails, packer fails to correctly identify each plugin path.

![image](https://user-images.githubusercontent.com/53507599/153780230-6f78fb18-8a2c-45a9-8be9-b5346c166a16.png)

**Comment by nlsickler** [comment] 2022-02-14 00:48
In the event someone stumbles on this and wants a work-around, if you have Packer managing Packer, you can pin the plugin to the previous commit.

```
return require('packer').startup(function()
  -- Allow Packer to update Packer
  use {'wbthomason/packer.nvim', commit = 'c5e98e3ca84843dbae47cd8f3a76bc38c6404241' }
end)
```

Pinning packer to the previous version stops every plugin from being overwritten constantly.

Just remember to follow and unpin it once this issue is resolved.

**Comment by Sewdohe** [comment] 2022-02-14 01:58
I was panicking  so hard...

**Comment by bryant-the-coder** [comment] 2022-02-14 02:39
this happens to me also

**Comment by WhyAre** [comment] 2022-02-14 03:00
> I'm still having the issue with this after pinning the last commit and clearing nvim and nvim-data folder before running PackerSync. Every run it asks me to remove all directories.

I would go to the git directory where packer.nvim was cloned to, and just run ```git reset --hard c5e98e3ca84843dbae47cd8f3a76bc38c6404241``` and packer should roll back to that version.

Another workaround (other than reverting to previous version of packer), would be to use the `as` key. So something like:
```
use {'tree-sitter/tree-sitter', as="treesitter"}
```

This seems to work for me, for now.

**Comment by bryant-the-coder** [comment] 2022-02-14 03:39
y treesitter as treesitter?

**Comment by WhyAre** [comment] 2022-02-14 03:44
It just has to be a name, because now packer fails to extract only the repo name. It treats the name as ```tree-sitter/tree-sitter``` and the cloned directory will be one level deeper. So by specifying `as`, you're just helping packer to clone the repo to the correct place.

**Comment by bryant-the-coder** [comment] 2022-02-14 03:51
¯\_(ツ)_/¯ thx bud... i thought my conf broke

**Comment by bryant-the-coder** [comment] 2022-02-14 10:58
any fix@wbthomason ?

**Comment by joshij1979** [comment] 2022-02-14 15:48
@wbthomason ..  any of the shared workarounds are not working...  every time I issue "PackerSync" the program asks to remove installed packages. The existing config is now broken :( any help would be appreciated.

**Comment by Sewdohe** [comment] 2022-02-14 15:57
Yeah, this is a serious issue for Windows users. Hopefully a fix will be merged today! If not I will try and take a look at it when I get off of work tonight and see what I can do.

**Comment by wbthomason** [comment] 2022-02-14 19:01
Shoot, sorry - I"ll revert the PR that caused this, then investigate. Didn't get the notifications from mentions, for some reason.

**Comment by wbthomason** [comment] 2022-02-14 19:02
I've reverted 75d70d4 in 66d67bb

**Comment by wbthomason** [comment] 2022-02-14 19:03
Sorry for the breakage - I'll try to figure out an actual fix for #802 that doesn't break Windows (though limited testing indicated #807 was OK)

**Comment by limeless** [comment] 2022-02-15 02:08
> Tagging @Sewdohe @joshij1979 @bryant-the-coder @WhyAre @nlsickler @samr @TheLeoP @tmhys @younger-1 @limeless @Some-Dood @dtr2300 to make sure you know the break was rolled back.

After revert it's working on Windows now, thanks for reverting.

**Comment by ritchielrez** [comment] 2022-02-15 05:20
This is problem seems to be fixed now, using **Neovim** 0.6.1 and **Windows 11**. Run **:PackerSync** and update packer.nvim. That should fix the problem! I spend my whole day to figure out what the problem was, turns out it was a bug.
Fortunately, I figured it out today, thanks to @wbthomason for fixing the change quickly 🎉

**Comment by Sewdohe** [comment] 2022-02-15 05:21
why did this get re-opened?

**Comment by ritchielrez** [comment] 2022-02-15 05:21
Yeah the problem seems to be fixed.

**Comment by Sewdohe** [comment] 2022-02-15 05:58
> Yeah the problem seems to be fixed.

I guess he re-opened it just to let us know it was reverted?

**Comment by wbthomason** [comment] 2022-02-15 17:48
It was re-opened until I got confirmation that reverting did fix the issue.

**Closed by wbthomason** 2022-02-15 17:48 UTC
Labels: bug
