### ISSUE TITLE
Error in Packer commands

### ISSUE THREAD

**Issue by Tinku10** [wbthomason/packer.nvim#463] opened 2021-07-09 04:14 UTC
![bug](https://user-images.githubusercontent.com/29244595/125021480-5a536e00-e098-11eb-89f0-2a66da9f325a.png)

- `nvim --version`: 0.5
- `git --version`: 2.25.1
- Operating system/version: Ubuntu 20.04
- Terminal name/version: Kitty 0.20.2

### Steps to reproduce
Using any ```Packer``` commands will produce this error.

### Actual behaviour
Passing a ```nil``` argument to ```fmt```.
https://github.com/wbthomason/packer.nvim/blob/c03bdafcaf000ffe422a31c7b450641ebd644041/lua/packer/plugin_types/git.lua#L87

### Expected behaviour
Should run the command successfully.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

[Link](https://github.com/Tinku10/LightNvim/blob/main/lua/settings/plugins.lua)

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here
[DEBUG Wednesday 07 July 2021 10:11:15 AM 6120997263402] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Wednesday 07 July 2021 10:11:15 AM 6121065118199] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:11:31 AM 6136557224580] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:379: packer.update: requiring modules
[DEBUG Wednesday 07 July 2021 10:11:31 AM 6136557384476] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:11:35 AM 6140533426188] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:12:16 AM 6181479301490] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:12:43 AM 6209040806050] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:12:54 AM 6220168075037] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:13:11 AM 6237064910436] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:13:53 AM 6279167686576] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:15:18 AM 6363558931574] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:15:26 AM 6372186480203] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:15:32 AM 6377678943042] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:15:36 AM 6381508334263] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:16:28 AM 6434358784225] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:16:31 AM 6436552726636] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:17:08 AM 6474311363992] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:17:11 AM 6476622942780] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:17:44 AM 6510237395005] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:17:55 AM 6520533408952] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:05 AM 6531049022958] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:09 AM 6534772903403] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:18 AM 6543997236939] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:315: packer.install: requiring modules
[DEBUG Wednesday 07 July 2021 10:18:18 AM 6543999144907] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:33 AM 6558486825030] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:45 AM 6570799340180] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:49 AM 6575311716332] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:18:56 AM 6581550608238] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:19:13 AM 6598855588912] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:19:53 AM 6638771260900] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:20:16 AM 6661639448426] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:24:01 AM 6886721494989] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:24:10 AM 6895899857129] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:24:12 AM 6898367951223] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:29:49 AM 7235036362571] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:33:47 AM 7472551199791] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Wednesday 07 July 2021 10:33:47 AM 7472553745943] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:33:52 AM 7477463254967] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:34:41 AM 7526486181119] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:34:48 AM 7533799835789] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:379: packer.update: requiring modules
[DEBUG Wednesday 07 July 2021 10:34:48 AM 7533801983215] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:34:51 AM 7536672048249] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:36:13 AM 7619282828695] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:36:36 AM 7641865570199] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 10:36:41 AM 7647185575961] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 12:34:25 PM 13832934277352] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:315: packer.install: requiring modules
[DEBUG Wednesday 07 July 2021 12:34:25 PM 13832935742080] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 12:34:30 PM 13837014325082] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 04:35:35 PM 24518730563189] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Wednesday 07 July 2021 04:35:36 PM 24519663186261] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 06:29:13 PM 31071990314188] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Wednesday 07 July 2021 06:53:55 PM 32554128482989] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Thursday 08 July 2021 07:36:45 PM 36339753556049] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Thursday 08 July 2021 07:36:45 PM 36339811681942] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Friday 09 July 2021 08:46:40 AM 936948717633] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Friday 09 July 2021 08:46:40 AM 937106435808] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Friday 09 July 2021 08:46:48 AM 945661587220] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Friday 09 July 2021 09:08:16 AM 2233738634206] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Friday 09 July 2021 09:10:34 AM 2371735620378] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs
[DEBUG Friday 09 July 2021 09:16:19 AM 2715849056177] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:448: packer.sync: requiring modules
[DEBUG Friday 09 July 2021 09:16:19 AM 2715858537707] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:272: Processing plugin specs

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here
[Link](https://github.com/Tinku10/LightNvim/blob/main/plugin/packer_compiled.lua)
</details>

**Comment by wbthomason** [comment] 2021-07-09 05:04
Thanks for the report! Interestingly, I cannot reproduce this - every command works fine for me. Did this start recently? If so, if you have a chance to do a `git bisect` that would be extremely helpful.

**Comment by wbthomason** [comment] 2021-07-09 05:06
You could also try putting a `require(packer.log).error(vim.inspect(err))` at line 78 of `lua/packer/plugin_types/git.lua` so that we can confirm that the issue is that the `table.concat` result on line 80 (which is the 3rd argument to `fmt`) is indeed `nil`.

**Comment by Tinku10** [comment] 2021-07-09 11:50
> require(packer.log).error(vim.inspect(err)) 

Adding this at line 78 of  ```lua/packer/plugin_types/git.lua``` did'nt give me any result. Maybe I'm doing something wrong.
But doing a print before line 87 of the same file gives these result

```config.depth``` has a value ```1```
```plugin.commit``` has a ```nil``` value

@wbthomason I don't know how to do git bisect, but I'll try to use it.

**Comment by Tinku10** [comment] 2021-07-09 12:16
I tried ```git bisect```. I went as far as https://github.com/wbthomason/packer.nvim/commit/b76bfba54031ad28f17e98ef555e99cf450d6cb3. Even in this commit I got a message saying ```Passing nil value to table```, but I was able to run ```PackerSync``` which led to this error.

But because of ```PackerSync``` the ```packer.nvim``` directory was deleted, but because of the error it did not pull the latest commits and the directory remained empty. So```git bisect``` could not be carried on.

Now I pulled ```packer``` again manually as I had no options. And everything is working now. 

So I am not sure which commit introduced that bug @wbthomason. Thanks for your help.

**Comment by wbthomason** [comment] 2021-07-09 15:15
Thanks for trying that. I'm not really sure what happened here - the `packer.nvim` directory should not have been deleted, as you specify `packer` as a managed plugin in the plugin spec file you linked. My best guess is that you weren't on the latest `packer` (since your line 87 of `git.lua` probably cannot match the line 87 in the latest version, since that's not a place we use `fmt`) and Neovim updates broke the old `packer`, or maybe that your `git` state somehow became broken in a way that we don't account for in the code.

Thanks again for the work in trying to narrow this down. I'm going to close this for now as things seem to be working, but let's re-open if it starts happening again.

**Closed by wbthomason** 2021-07-09 15:15 UTC
Labels: bug
