### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by huyvohcmc** [wbthomason/packer.nvim#126] opened 2020-12-19 06:49 UTC
Neovim version: NVIM v0.5.0-dev+950-g5ce328df401b
OS: MacOS Catalina
Git version: 2.29.2

`:PackerSync` result:
```
Error executing vim.schedule lua callback: .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:48: bad argument #1 to 'max' (number expected, got no value)
```
![Screen Shot 2020-12-19 at 1 46 47 PM](https://user-images.githubusercontent.com/17645203/102683045-a4f6c100-4200-11eb-8c83-571eeb95bf97.png)
Plugin `fatih/vim-go` stuck at `checking updated commit...`, but sometimes it happens on other plugins, and the message is also different per update (checking updated commit, getting commit messages...).

My [plugins.lua](https://github.com/huyvohcmc/dotfiles/blob/master/nvim/lua/plugins.lua).

**Comment by wbthomason** [comment] 2020-12-19 18:48
What is your `packer.nvim` version? A problem like this was recently patched in #103.

**Comment by huyvohcmc** [comment] 2020-12-20 02:00
The last commit in my machine is 27 Nov, so it's very outdated. After a manual git pull it's okay now

**Comment by wbthomason** [comment] 2020-12-20 03:52
Ok, I'm closing this as a duplicate of #103, then. Feel free to reopen if you encounter the issue again.

**Closed** 2020-12-20 03:53 UTC
