### ISSUE TITLE
PackerClean window not showing

### ISSUE THREAD

**Issue by seblj** [wbthomason/packer.nvim#354] opened 2021-05-12 11:29 UTC
- `nvim --version`: NVIM v0.5.0-dev+1318-g61aefaf29
- `git --version`: 2.31.1
- Operating system/version: macOS Big Sur 11.3
- Terminal name/version: iTerm2 Build 3.4.20210426-nightly

When running `PackerClean`, the window showing the plugins to be removed is not popping up. I thought I could open an issue here about this in case it's something that could be done here.

However, I think the issue is related to this: https://github.com/neovim/neovim/issues/14524. 

The same commit that broke his plugin is the same commit that broke the window for me in packer.

**Comment by akinsho** [comment] 2021-05-12 12:41
Thanks for raising this @seblj I actually had a tab open where I was going to report the same thing. I've actually had this issue since before that particular commit got merged into nvim but maybe it might point to a reason why it's happening so thanks for linking it.

**Comment by wbthomason** [comment] 2021-05-18 19:43
Thanks for the report! I'm not sure I understand why not blocking autocommands would cause this behavior, but I can reproduce the bug. One option is to wait and see if upstream introduces a fix or reverts the commit, but that seems like it'll leave `packer.clean` broken for a long time. Maybe we try the `eventignore` workaround mentioned in that commit thread?

**Comment by akinsho** [comment] 2021-05-18 20:11
@wbthomason I might have misunderstood since I was watching from a distance but a series of patches was merged which I think, they hoped would include a fix, so they wouldn't have to revert. Though since the bug still persists seems like it didn't. In either case I've actually been seeing this issue sporadically for a while now so not sure it's down to just that commit although it might have made it worse.

**Comment by wbthomason** [comment] 2021-05-18 20:28
Hmm, ok. It seems like we'll need to do some debugging to figure out if this is the window failing to open, opening and immediately closing, etc.

**Comment by seblj** [comment] 2021-05-18 20:31
I think the window is there, but outside og the screen. If I have a terminal window in the top left corner and run PackerClean, nothing shows. But if I then make it fullscreen before I do something else, the window is shown, but is out of place from where it should be

**Comment by seblj** [comment] 2021-05-18 20:47
https://user-images.githubusercontent.com/5160701/118721316-f98f7e00-b82a-11eb-880f-22b4ac396cb2.mov

**Comment by seandewar** [comment] 2021-06-01 11:18
Just a heads up that https://github.com/neovim/neovim/pull/14659 was merged, which adds a `noautocmd` option to `nvim_open_win` to restore the old behaviour.

**Comment by wbthomason** [comment] 2021-06-03 04:54
Thanks for the notification, @seandewar! This should be fixed now; please let me know if you continue to encounter issues.

**Closed** 2021-06-03 04:54 UTC
Labels: bug, neovim_bug
